# Generated by Django 5.0.4 on 2024-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={"verbose_name": "Дневник", "verbose_name_plural": "Дневники"},
        ),
        migrations.AlterModelOptions(
            name="note",
            options={"verbose_name": "Страница", "verbose_name_plural": "Страницы"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Список пользователей",
            },
        ),
    ]
